export const PROJECT_NAME = 'CRISBOARNA';

export const ENV = 'ENV';

export const CLOUD_DEPLOYED = 'CLOUD_DEPLOYED';

export const DOMAIN_NAME = 'DOMAIN_NAME';

export const REGION = 'REGION';

export const SES_EMAIL_NAME = 'SES_EMAIL_NAME';

export const INFRA_GATEWAY_HEADER_AUTH_KEY = 'INFRA_GATEWAY_HEADER_AUTH_KEY';
export const INFRA_GATEWAY_HEADER_AUTH_VALUE =
  'INFRA_GATEWAY_HEADER_AUTH_VALUE';

export const INFRA_CDN_HEADER_AUTH_KEY_NAME = `/${PROJECT_NAME.toLowerCase()}/lambda/api/auth/cdn/header/key/`;
export const INFRA_CDN_HEADER_AUTH_KEY = 'INFRA_CDN_HEADER_AUTH_KEY';
export const INFRA_CDN_HEADER_AUTH_VALUE = `INFRA_CDN_HEADER_AUTH_VALUE`;
export const INFRA_CDN_HEADER_AUTH_VALUE_NAME = `/${PROJECT_NAME.toLowerCase()}/lambda/api/auth/cdn/challenge/`;

export const INFRA_CDN_CHALLENGE_USER = 'INFRA_CDN_CHALLENGE_USER';
export const INFRA_CDN_CHALLENGE_PASSWORD = 'INFRA_CDN_CHALLENGE_PASSWORD';
